version: "3.9"

services:
  backend:
    build: ./shoppit
    container_name: django-backend
    env_file:
      - .env
    volumes:
      - ./shoppit:/app
      - media:/app/media
      - static:/app/staticfiles
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
    restart: always
    networks:
      - shoppit_network

  frontend:
    build: ./client
    container_name: react-frontend
    ports:
      - "5173:80" # Changed to 3000 (standard React) or keep 80 if using Nginx
    depends_on:
      - backend
    restart: always
    networks:
      - shoppit_network

  mongodb:
    image: mongo:7
    container_name: mongodb
    restart: always
    environment:
      - MONGO_INITDB_DATABASE=shoppit_db # Fixed indentation & format
    volumes:
      - mongo_data:/data/db
    expose:
      - "27017"
    networks:
      - shoppit_network

networks:
  shoppit_network:
    driver: bridge

volumes:
  mongo_data:
  media:
  static:
